### ISSUE TITLE
Laravel 5.2 -Error "Class queue does not exist"

### ISSUE THREAD

**Issue by mashur** [dusterio/laravel-plain-sqs#1]
Laravel 5.2

Followed all instructions exactly and receiving the following error "Class queue does not exist".

```
[2016-05-21 18:11:07] local.ERROR: exception 'ReflectionException' with message 'Class queue does not exist' in /var/www/xtr/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
Stack trace:
#0 /var/www/xtr/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('queue')
#1 /var/www/xtr/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('queue', Array)
#2 /var/www/xtr/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('queue', Array)
#3 /var/www/xtr/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('queue')
#4 /var/www/xtr/vendor/dusterio/laravel-plain-sqs/src/Integrations/LaravelServiceProvider.php(36): Illuminate\Container\Container->offsetGet('queue')
#5 /var/www/xtr/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(554): Dusterio\PlainSqs\Integrations\LaravelServiceProvider->register()
#6 /var/www/xtr/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(74): Illuminate\Foundation\Application->register(Object(Dusterio\PlainSqs\Integrations\LaravelServiceProvider))
#7 /var/www/xtr/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Foundation\ProviderRepository->load(Array)
#8 /var/www/xtr/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#9 /var/www/xtr/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#10 /var/www/xtr/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#11 /var/www/xtr/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#12 /var/www/xtr/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}  

```

**Comment by mashur** [comment]
Seems to fix https://github.com/dusterio/laravel-plain-sqs/pull/2

**Comment by dusterio** [comment]
I'm using Lumen so I haven't properly tested it with Laravel - thanks for the fix!
